### ISSUE TITLE
Installation Guide

### ISSUE THREAD

**Issue by Martijnpold** [ZeroniaServer/RocketRiders#1]
Hey there! I'd love to try out this project (and maybe contribute in some way if I have any ideas). Could you please include a simple step by step on how to run it and what version to run it on?

**Comment by Evtema3** [comment]
Hello - currently the game is still under private development. We are aiming for a release of the full map soon, and that will serve as the development environment for any prospective contributors to the project. We appreciate the interest, and stay tuned! :)

**Comment by Evtema3** [comment]
@Martijnpold Hello - sorry for the long wait. The map just released publicly today (literally right as I send this)!

You can download it [here](https://www.planetminecraft.com/project/rocket-riders/) from Planet Minecraft.

There is an installation guide on that page, or alternatively, you can find one [here](https://zeroniaserver.github.io/RocketRidersWiki/installation_guide.html).

Please open a new issue if you have any further questions!
